Transport/src/Entity/Transport.php
<?php

namespace App\Entity;

use App\Repository\TransportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TransportRepository::class)
 */
class Transport
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $Prix_tr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Type_tr; /* autre table  */

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Disponibilite_tr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Id_groupe_tr; /*id randonnee : clé étrangère */

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Destination_tr;

    /**
     * @ORM\Column(type="integer")
     */
    private $Stock_tr; /* capacité */

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image_tr;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrixTr(): ?float
    {
        return $this->Prix_tr;
    }

    public function setPrixTr(float $Prix_tr): self
    {
        $this->Prix_tr = $Prix_tr;

        return $this;
    }

    public function getTypeTr(): ?string
    {
        return $this->Type_tr;
    }

    public function setTypeTr(string $Type_tr): self
    {
        $this->Type_tr = $Type_tr;

        return $this;
    }

    public function getDisponibiliteTr(): ?string
    {
        return $this->Disponibilite_tr;
    }

    public function setDisponibiliteTr(string $Disponibilite_tr): self
    {
        $this->Disponibilite_tr = $Disponibilite_tr;

        return $this;
    }

    public function getIdGroupeTr(): ?string
    {
        return $this->Id_groupe_tr;
    }

    public function setIdGroupeTr(string $Id_groupe_tr): self
    {
        $this->Id_groupe_tr = $Id_groupe_tr;

        return $this;
    }

    public function getDestinationTr(): ?string
    {
        return $this->Destination_tr;
    }

    public function setDestinationTr(string $Destination_tr): self
    {
        $this->Destination_tr = $Destination_tr;

        return $this;
    }

    public function getStockTr(): ?int
    {
        return $this->Stock_tr;
    }

    public function setStockTr(int $Stock_tr): self
    {
        $this->Stock_tr = $Stock_tr;

        return $this;
    }

    public function getImageTr()
    {
        return $this->Image_tr;
    }

    public function setImageTr( $Image_tr): self
    {
        $this->Image_tr = $Image_tr;

        return $this;
    }
}

Transport/src/Form/TransportType.php
<?php

namespace App\Form;

use App\Entity\Transport;
use phpDocumentor\Reflection\Type;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TransportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Prix_tr',TextType::class,[
                'label'=>'Prix Transport',
                'attr'=>[
                    'placeholder'=>'Merci de definir le prix',
                    'calss'=>'prix'
                ]

            ])
            ->add('Type_tr')
            ->add('Disponibilite_tr')
            ->add('Id_groupe_tr')
            ->add('Destination_tr')
            ->add('Stock_tr')
            ->add('Image_tr', FileType::class , array('data_class'=>null, 'required'=>false))


        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Transport::class,
        ]);
    }



}

Transport/src/Controller/TransportController.php
<?php

namespace App\Controller;

use App\Entity\Transport;
use App\Form\TransportType;
use App\Repository\TransportRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;

class TransportController extends AbstractController
{
    /**
     * @Route("/transport", name="transport")
     */
    public function index(): Response
    {
        return $this->render('transport/index.html.twig', [
            'controller_name' => 'TransportController',
        ]);
    }


    /**
     * @param TransportRepository $repository
     * @return Response
     * @Route("/AfficheTransport",name="AfficheTransport")
     */
    public function Affiche(TransportRepository $repository){
       // $repository=$this->getDoctrine()->getRepository(Transport::class);
        $em=$this->getDoctrine()->getManager();
        $Transport=$repository->findAll();
        return $this->render('Transport/Affiche.html.twig',
        ['Transport'=>$Transport]);



    }


    /**
     * @Route("/Supp/{id}",name="d")
     */
    function Delete($id,TransportRepository $repository){
        $Transport=$repository->find($id);
        $em=$this->getDoctrine()->getManager();
        $em->remove($Transport);
        $em->flush();
        $this->addFlash("Success",'Post was removed');
        return $this->redirectToRoute('AfficheTransport');

    }

    /**
     * @param Request $request
     * @return Response
     * @Route("transport/Add")
     */
    function Add(Request $request){
        $transport=new transport();
        $form=$this->createForm(transportType::class,$transport);
        $form->add('Ajouter',SubmitType::Class);
        $form->handleRequest($request);
        if($form->isSubmitted()&& $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $file=$transport->getImageTr();
            $filename= md5(uniqid())   .  '.'  .  $file->guessExtension();
            $file->move ($this->getParameter('upload_directory'),$filename);
            $transport->setImageTr($filename);

            $em->persist($transport);
            $em->flush();

            $this->addFlash('info', 'Created Successfully !');
            return $this->redirectToRoute('AfficheTransport');
        }
        return $this->render('transport/add.html.twig',[
            'form'=>$form->createView()

        ]);


    }

    public function addAction(Request $request)
    {

        $post = new Post();
        $form= $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $em = $this->getDoctrine()->getManager();

            $file = $post->getPhoto();
            $filename= md5(uniqid()) . '.' . $file->guessExtension();
            $file->move($this->getParameter('photos_directory'), $filename);
            $post->setPhoto($filename);
            $post->setCreator($this->getUser());
            $post->setPostdate(new \DateTime('now'));

            $em->persist($post);
            $em->flush();

            $this->addFlash('info', 'Created Successfully !');
        }
        return $this->render('@TutorialBlog/Post/add.html.twig', array(
            "Form"=> $form->createView()
        ));
    }
    /**
     * @Route("transport/update/{id}",name="update")
     */
    function update(TransportRepository  $repository,$id,Request $request){
        $Transport=$repository->find($id);
        $form=$this->createForm(TransportType::class,$Transport);
        $form->add('update',SubmitType::class);
        $form->handleRequest($request);
        if($form->isSubmitted()&& $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("AfficheTransport");

        }
        return $this->render('transport/update.html.twig',[
            'form'=>$form->createView()

        ]);
    }

    /**
     * @param Request $request
     * @return Response
     * @Route("/ajax_search", name="ajax_search",methods={"GET"})
     */
    public function searchAction(Request $request, $Transport)
    {
        $em = $this->getDoctrine()->getManager();
        $requestString = $request->get('q');
        $Transport =  $em->Repository->findEntitiesByString($requestString);
        if(!$Transport) {
            $result['Transport']['error'] = "Transport Not found :( ";
        } else {
            $result['Transport'] = $this->getRealEntities($Transport);
        }
        return new Response(json_encode($result));
    }
    public function getRealEntities($Transport){
        foreach ($Transport as $Transport){
            $realEntities[$Transport->getId()] = [$Transport->getImageTr(),$Transport->getType()];

        }
        return $realEntities;
    }

    /**
     * @param TransportRepository $repository
     * @return Response
     * @Route("/detailedT/{id}",name="detailedt",methods={"GET"})
     */
    public function showdetailedAction($id, TransportRepository $repository)
    {
        $em= $this->getDoctrine()->getManager();
        $Transport=$repository->find($id);
        $form=$this->createForm(TransportType::class,$Transport);
        $form->add('Detail',SubmitType::class,[
            'attr'=>[
                'class'=>'btn-primary waves-effect waves-light'
            ]
        ]);



        return $this->render('transport/detailedpost.html.twig', [
            'Type_tr'=>$Transport->getTypeTr(),
            'Disponibilite_tr'=>$Transport->getDisponibiliteTr(),
            'Image_tr'=>$Transport->getImageTr(),
            'Destination_tr'=>$Transport->getDestinationTr(),
            'Stock_tr'=>$Transport->getStockTr(),
            'Prix_tr'=>$Transport->getPrixTr(),
            'Id_groupe_tr'=>$Transport->getIdGroupeTr(),
            'id'=>$Transport->getId()
        ]);
    }


    /**
     * @param TransportRepository $repository
     * @return Response
     * @Route("/mypdf", name="mypdf",methods={"GET"})
     */
    public function mypdf(TransportRepository $repository)
    {
        $Transport = $repository->findAll();

        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);


        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('Transport/mypdf.html.twig',
            ['Transport' => $Transport
            ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (inline view)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => false
        ]);


    }

}

Transport/templates/transport/Add.html.twig
{% extends 'index.html.twig' %}

{% block body %}



    <div class="row small-spacing">
        <div class="col-md-8">
            <div class="box-content card black">
                <h4 class="box-title">Add Transport</h4>
                <br>
                <!-- /.box-title -->
                <div class="card-content">

                    {{ form_start(form) }}


                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Prix_tr) }}</label>
                        {{ form_widget(form.Prix_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter prix', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Type_tr) }}</label>
                        {{ form_widget(form.Type_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter type', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Disponibilite_tr) }}</label>
                        {{ form_widget(form.Disponibilite_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter disponibilite', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Id_groupe_tr) }}</label>
                        {{ form_widget(form.Id_groupe_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter id groupe', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Destination_tr) }}</label>
                        {{ form_widget(form.Destination_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter destination', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Stock_tr) }}</label>
                        {{ form_widget(form.Stock_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter stock', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Image_tr) }}</label>
                        {{ form_widget(form.Image_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter image', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <br>
                </div>

                {{ form_row(form.Ajouter, {'attr': {'class': 'btn btn-primary btn-sm waves-effect waves-light'}, 'label': 'Ajouter' }) }}

                {{ form_end(form) }}
            </div>
            <!-- /.card-content -->
        </div>
        <!-- /.box-content -->
    </div>

    </div>



{% endblock %}

Transport/templates/transport/Affiche.html.twig
{% extends 'index.html.twig' %}
    {% block body %}

        {% for message in app.flashes('Success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        <!-- Start Styles. Move the 'style' tags and everything between them to between the 'head' tags -->
        <style type="text/css">
            .myTable { background-color: #ccb59f;border-collapse:collapse; }
            .myTable th { background-color: #25241b;color: #ded6d6;width:50%; }
            .myTable td, .myTable th { padding:5px;border:1px solid #211e10; }
        </style>
        <!-- End Styles -->

        <a href="c" class="filled-button">Affiche calendar</a><hr><br>

        <h1>Lists of Transport !</h1>

        <div class="album py-5 bg-light">
            <div class="container">

                <h2>Search A Post !!</h2>

                <div class="sidebar-search">

                    <div class="input-group custom-search-form">

                        <input type="text" id="search" class="form-control" placeholder="Search here">
                    </div>
                    <!-- /input-group -->
                </div>
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="#"> Entities<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level" id="entitiesNav">
                        </ul>
                    </li>
                </ul><br><br><br><br>

                <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

                <script type="text/javascript">
                    jQuery(document).ready(function() {
                        var searchRequest = null;
                        $("#search").keyup(function() {
                            var minlength = 1;
                            var that = this;
                            var value = $(this).val();
                            var entitySelector = $("#entitiesNav").html('');
                            if (value.length >= minlength ) {
                                if (searchRequest != null)
                                    searchRequest.abort();
                                searchRequest = $.ajax({
                                    type: "GET",
                                    url: "{{ path('ajax_search') }}",
                                    data: {
                                        'q' : value
                                    },
                                    dataType: "text",
                                    success: function(msg){
                                        //we need to check if the value is the same
                                        if (value===$(that).val()) {
                                            var result = JSON.parse(msg);
                                            $.each(result, function(key, arr) {
                                                $.each(arr, function(id, value) {
                                                    if (key === 'Transport') {
                                                        if (id !== 'error') {
                                                            console.log(value[1]);
                                                            entitySelector.append('<li><b>'+value[1]+'</b><a href="/AfficheTransport/'+id+'">'+'<img src="/uploads/'+value[0]+'" style="width: 50px; height: 50px"/>'+'</a></li>');
                                                        } else {
                                                            entitySelector.append('<li class="errorLi">'+value+'</li>');
                                                        }
                                                    }
                                                });
                                            });
                                        }
                                    }
                                });
                            }
                        });
                    });
                </script>


                <div class="post-container">
                    <div class="row">


                        <section class="featured section-padding">
                            <div class="container">
                                <div class="row">
                                    <div class="col-12 text-center">
                                        <div class="heading">
                                            <h1 class="section-title">Latest Transport</h1><br>
                                            <h4 class="sub-title">You can also post your own Transport</h4><hr><br>
                                        </div>
                                    </div>

                                    {% for t in Transport %}

                                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
                                            <div class="featured-box">
                                                <figure>
                                                    <a href="{{ path('detailedt',{'id': t.id}) }}"><img class="card-img-top" src="{{ asset('uploads/' ~ t.imageTr) }}" alt="Card image cap"></a>
                                                </figure>
                                                <div class="content-wrapper">
                                                    <div class="feature-content">
                                                        <h4><a href="{{ path('detailedt',{'id': t.id}) }}">->{{ t.typeTr }}</a></h4>
                                                        <p class="listing-tagline">-{{ t.prixTr }} $</p>
                                                        <div class="meta-tag">
                                                            <div class="listing-review">
                                                                <span class="review-avg">4.5</span>
                                                                2 Ratings
                                                            </div>
                                                            <div class="user-name">
                                                                <a href="#"><i class="lni-user"></i>-{{ t.destinationTr }}</a>
                                                            </div>
                                                            <div class="listing-category">
                                                                <a href="#"><i class="lni-alarm-clock"></i>-{{ t.disponibiliteTr }} </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="listing-bottom clearfix">
                                                        <div class="btn-group">
                                                            <a href="{{ path('AfficheTransport',{'id': t.id}) }}"><button type="button" class="btn btn-sm btn-outline-primary">View</button></a>

                                                        </div>
                                                    </div>
                                                </div>

                                            </div>

                                        </div>
                                    {% endfor %}

                                </div>
                            </div>

                        </section>



                    </div>

                </div>
            </div>
        </div>

        <a href="transport/Add" class="filled-button">Add Transport</a>  <a href="/calendar/new" class="filled-button">Add Calendar</a>

    {% endblock %}

Transport/templates/transport/calandar.html.twig
{% extends 'index.html.twig' %}

{% block title %}Calendrier{% endblock %}

{% block stylesheets %}
    <style>
        #calendrier{
            width: 80%;
            margin: auto;
        }
    </style>
{% endblock %}

{% block body %}
    <div id="calendrier">
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        window.onload = () => {
            let calendarElt = document.querySelector("#calendrier")
            let calendar = new FullCalendar.Calendar(calendarElt, {
                initialView: 'timeGridWeek',
                locale: 'fr',
                timeZone: 'Europe/Paris',
                headerToolbar: {
                    start: 'prev,next today',
                    center: 'title',
                    end: 'dayGridMonth,timeGridWeek'
                },
                events: {{ data|raw }},
                editable: true,
                eventResizableFromStart: true
            })
            calendar.on('eventChange', (e) => {
                let url = `/api/${e.event.id}/edit`
                let donnees = {
                    "title": e.event.title,
                    "description": e.event.extendedProps.description,
                    "start": e.event.start,
                    "end": e.event.end,
                    "backgroundColor": e.event.backgroundColor,
                    "borderColor": e.event.borderColor,
                    "textColor": e.event.textColor,
                    "allDay": e.event.allDay
                }

                let xhr = new XMLHttpRequest
                xhr.open("PUT", url)
                xhr.send(JSON.stringify(donnees))
            })
            calendar.render()
        }
    </script>

{% endblock %}

Transport/templates/transport/detailedpost.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <!-- Page Content -->
    <div class="container">
    <h1> Transport Details </h1><hr><br><br>


    <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">->{{ Type_tr|upper }}</h1>

        <!-- Author -->
        <p class="lead">

            <a href="{{ path('AfficheTransport') }}"class="filled-button">Go Home</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <h6>->{{ Disponibilite_tr }}</h6>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="{{ asset('uploads/' ~ Image_tr) }}" alt="{{ Type_tr }}">

        <hr><br>

        <!-- Post Content -->
        <h6 class="">->{{ Destination_tr }}</h6><hr>

        <h6 class="">->{{ Prix_tr }}$</h6><hr>

        <h6 class="">->{{ Id_groupe_tr }}</h6><hr>

        <h6 class="">->{{ Stock_tr }}  Place</h6><hr>



        <hr>






        </div>
        <br><br><br><br><br>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Search Widget -->





        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

{% endblock %}

Transport/templates/transport/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TransportController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/PC/Desktop/projet php transport/Transport/src/Controller/TransportController.php'|file_link(0) }}">src/Controller/TransportController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/PC/Desktop/projet php transport/Transport/templates/transport/index.html.twig'|file_link(0) }}">templates/transport/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

Transport/templates/transport/mypdf.html.twig
<h1>Liste de Transport PDF</h1>


<table class="myTable">
    <tr>
        <th>Prix</th>
        <th>Type</th>
        <th>Disponibilite</th>
        <th>ID_groupe</th>
        <th>Destination</th>
        <th>Stock</th>
        <th>Image</th>
    </tr>
    <tr {% for t in Transport%}>

        <td>{{ t.PrixTr }}</td>
        <td>{{ t.TypeTr }}</td>
        <td>{{ t.DisponibiliteTr}}</td>
        <td>{{ t.IdGroupeTr}}</td>
        <td>{{ t.DestinationTr}}</td>
        <td>{{ t.StockTr }}</td>
        <td>{% for image in t.imageTr %}
                <img src="{{ asset ('/uploads/' ~ image.name ) }}" alt="image" width="150">
            {% endfor %}
        </td>


    </tr{% endfor %}>
</table><hr>

Transport/templates/transport/update.html.twig
{% extends 'index.html.twig' %}
{% block body %}


    <div class="row small-spacing">
        <div class="col-xs-10">
            <div class="box-content card black">
                <h4 class="box-title">update Transport</h4>
                <br>
                <!-- /.box-title -->
                <div class="card-content">

                    {{ form_start(form) }}


                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Prix_tr) }}</label>
                        {{ form_widget(form.Prix_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter prix', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Type_tr) }}</label>
                        {{ form_widget(form.Type_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter type', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Disponibilite_tr) }}</label>
                        {{ form_widget(form.Disponibilite_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter disponibilite', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Id_groupe_tr) }}</label>
                        {{ form_widget(form.Id_groupe_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter id groupe', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Destination_tr) }}</label>
                        {{ form_widget(form.Destination_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter destination', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Stock_tr) }}</label>
                        {{ form_widget(form.Stock_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter stock', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form_label(form.Image_tr) }}</label>
                        {{ form_widget(form.Image_tr, {'attr': {'class': 'form-control', 'placeholder': 'Enter image', 'id': 'exampleInputEmail1', 'type': 'text'}}) }}
                    </div>
                    <br>
                </div>

                {{ form_row(form.update, {'attr': {'class': 'btn btn-primary btn-sm waves-effect waves-light'}, 'label': 'update' }) }}

                {{ form_end(form) }}
            </div>
            <!-- /.card-content -->
        </div>
        <!-- /.box-content -->
    </div>

    </div>
 {% endblock %}